version: '3.8'

services:
  pe-prediction-app:
    image: pe-prediction-app
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-east-1
      - S3_BUCKET=pe-prediction-app
      - MODEL_KEY=models/sagemaker-scikit-learn-2025-03-13-20-37-57-658/output/model.tar.gz
      - PORT=8080
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring: