name: Lint Python Code

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with SSH
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # Uses GitHub SSH key if set

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Using 3.8 for linting, while project runs on 3.7

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Isort (Sort Imports)
        run: isort scripts/

      - name: Run Black (Autoformat Code)
        run: black scripts/

      - name: Commit and Push Changes (if needed)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/
          if git diff --cached --quiet; then
            echo "No formatting changes needed."
          else
            git commit -m "Autoformatted code with Black and Isort [skip ci]"
            git push origin main
          fi

      - name: Run Flake8 (Linting)
        run: flake8 scripts/
        