name: Lint and Format Python Code

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Using 3.8 for the linter, while keeping scripts in 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Isort (Organize Imports)
        run: isort scripts/

      - name: Run Black (Autoformat Code)
        run: black scripts/

      - name: Run Flake8 (Linting)
        run: flake8 scripts/
      
      - name: Commit and Push Changes (if needed)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scripts/
          if git diff --cached --quiet; then
            echo "No formatting changes needed."
          else
            git commit -m "Autoformatted code with Black and Isort [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}