name: Lint and Format Python Code

on:
  push:
    branches:
      - main
      - develop
  pull_request:
permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"  # Linter only (project scripts still runs 3.7)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Autoformat Code (Black + isort)
        run: |
          black scripts/ --diff --color
          isort scripts/ --diff --color

      - name: Apply Black and Isort (Force changes)
        run: |
          black scripts/
          isort scripts/
          git status

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
          git add -A
          if git diff --cached --quiet; then
          echo "No changes detected. Skipping commit."
          exit 0
          fi

          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Autoformatted code with Black & Isort - ${timestamp}"
          git push origin main

      - name: Run Linter (flake8)
        run: flake8 scripts/