name: Lint Python Code

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3.7
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.7 python3.7-venv python3.7-dev
          python3.7 -m ensurepip --upgrade
          python3.7 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3.7 -m pip install flake8
          if [ -f requirements.txt ]; then python3.7 -m pip install -r requirements.txt; fi

      - name: Run Linter on scripts/
        run: python3.7 -m flake8 scripts/